### ISSUE TITLE
Data model should match Fauna gql meta descriptions

### ISSUE THREAD

**Issue by ptpaterson** [ptpaterson/fauna-fields-list-compiler#3]
Fauna docs provide examples of how a graphql schema can be represented.  https://docs.fauna.com/fauna/current/api/graphql/endpoints

Todo:
- [ ] Update `List` and `Non Null` representation
- [ ] Include directives, type-level and field-level.
- [ ] Update Typescript Types

Things to think about but will work on later:
- [ ] define the `Query` type's fields with directives and create helpers that will run the correct index based on the data model.  This will make GraphQL client resolvers even easier to use.

**Comment by ptpaterson** [comment]
`List` and `Non Null` example:

```js
type: { NotNull: { List: { NotNull: { Named: 'User' } } } }
```

index directive example

```js
directives: [ { name: 'index', args: { name: 'allUsers' } } ]
```
